# Generated by Django 4.2.7 on 2023-11-03 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memberNumber", models.IntegerField()),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=1000)),
                ("registrationDate", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staffNumber", models.IntegerField()),
                ("name", models.CharField(max_length=100)),
                ("position", models.CharField(max_length=50)),
                ("salary", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("catalogNumber", models.IntegerField()),
                ("videoNumber", models.IntegerField()),
                ("title", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("dailyRental", models.IntegerField()),
                ("cost", models.FloatField()),
                ("status", models.BooleanField()),
                ("mainActors", models.CharField(max_length=1000)),
                ("director", models.CharField(max_length=100)),
            ],
        ),
    ]
